spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2ze186x0og6jrp998fo.mysql.rds.aliyuncs.com:3306/kingcloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: xuzrg5CK@BvkyEP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        fromat-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  thymeleaf:
    cache: false
  redis:
    host: www.wuzhaoqi.top
    port: 6379
    database: 1
    password: kingRedis
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8


server:
  port: 8080
  servlet:
    session:
      timeout: 6000
    encoding:
      charset: UTF-8
      force: true


logging:
  level:
    root: warn
    org.springframework: warn
  file:
    path: ./logs
    name: king.log

swagger:
  enabled: true

# 文件上传暂存路径
file:
  UploadPath: F:/test/

